export const fruitsData = [
  {
    id: 1,
    name: "Apple",
    amount: 180,
    srcpath: process.env.PUBLIC_URL + "/images/Apples.jpg",
    inventory: 5,
    qty: 0,
    type: "fruits",
  },
  {
    id: 2,
    name: "Banana",
    amount: 30,
    srcpath: process.env.PUBLIC_URL + "/images/Banana.jpg",
    inventory: 5,
    qty: 0,
    type: "fruits",
  },
  {
    id: 3,
    name: "Grapes",
    amount: 160,
    srcpath: process.env.PUBLIC_URL + "/images/Grapes.jpg",
    inventory: 5,
    qty: 0,
    type: "fruits",
  },
  {
    id: 5,
    name: "Papaya",
    amount: 40,
    srcpath: process.env.PUBLIC_URL + "/images/Papaya.jpg",
    inventory: 5,
    qty: 0,
    type: "fruits",
  },
  {
    id: 6,
    name: "Kiwi",
    amount: 80,
    srcpath: process.env.PUBLIC_URL + "/images/Kiwi.jpg",
    inventory: 5,
    qty: 0,
    type: "fruits",
  },
  {
    id: 7,
    name: "Promogranet",
    amount: 45,
    srcpath: process.env.PUBLIC_URL + "/images/Promogranite.jpg",
    inventory: 5,
    qty: 0,
    type: "fruits",
  },
];
export const vegData = [
  {
    id: 1,
    name: "Roma Tomato",
    amount: 10,
    srcpath: process.env.PUBLIC_URL + "/images/Tomato.jpg",
    inventory: 5,
    qty: 0,
    type: "veg",
  },
  {
    id: 2,
    name: "Potato",
    amount: 10,
    srcpath: process.env.PUBLIC_URL + "/images/Potato.jpg",
    inventory: 5,
    qty: 0,
    type: "veg",
  },
  {
    id: 3,
    name: "Onion",
    amount: 15,
    srcpath: process.env.PUBLIC_URL + "/images/Onion.jpg",
    inventory: 5,
    qty: 0,
    type: "veg",
  },
  {
    id: 5,
    name: "Radish",
    amount: 12,
    srcpath: process.env.PUBLIC_URL + "/images/Radish.jpg",
    inventory: 5,
    qty: 0,
    type: "veg",
  },
  {
    id: 6,
    name: "Carrot",
    amount: 6,
    srcpath: process.env.PUBLIC_URL + "/images/Carrot.jpg",
    inventory: 5,
    qty: 0,
    type: "veg",
  },
  {
    id: 7,
    name: "Garlic",
    amount: 19,
    srcpath: process.env.PUBLIC_URL + "/images/Garlic.jpg",
    inventory: 5,
    qty: 0,
    type: "veg",
  },
  {
    id: 8,
    name: "Ginger",
    amount: 30,
    srcpath: process.env.PUBLIC_URL + "/images/Ginger.jpg",
    inventory: 5,
    qty: 0,
    type: "veg",
  },
  {
    id: 5,
    name: "Radish",
    amount: 12,
    srcpath: process.env.PUBLIC_URL + "/images/Radish.jpg",
    inventory: 5,
    qty: 0,
    type: "veg",
  },
  {
    id: 6,
    name: "Carrot",
    amount: 6,
    srcpath: process.env.PUBLIC_URL + "/images/Carrot.jpg",
    inventory: 5,
    qty: 0,
    type: "veg",
  },
  {
    id: 7,
    name: "Garlic",
    amount: 19,
    srcpath: process.env.PUBLIC_URL + "/images/Garlic.jpg",
    inventory: 5,
    qty: 0,
    type: "veg",
  },
  {
    id: 8,
    name: "Ginger",
    amount: 30,
    srcpath: process.env.PUBLIC_URL + "/images/Ginger.jpg",
    inventory: 5,
    qty: 0,
    type: "veg",
  },
];
